global using Microsoft.AspNetCore.Mvc;
global using Moq;
global using NUnit.Framework;
global using SuratBook.Services.Interfaces;
global using SuratBook.Services.Models.Group;
global using SuratBook.Services.Models.Photo;
global using SuratBook.Test.Mock;
global using SuratBook.Web.Controllers;
global using SuratBook.Web.Models;
